name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - main

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          version: 12.4.2

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: Building
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./dist
          branch: gh-pages
