name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.6
        with:
          version: 11.0.9

      - name: Installing Dependencies
        run: pnpm i

      - name: Building
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./dist
          branch: gh-pages
